In [1]:
import numpy as np

In [32]:
# Array 1D
d1 = np.array([1,5,4])
print(f'{d1.shape}\n{d1.ndim}\n{d1.dtype}\n')
print(d1)

(3,)
1
int64

[1 5 4]


In [33]:
# Array 2D
d2 = np.array([[1,5,4],[4,3,7]])
print(f'{d2.shape}\n{d2.ndim}\n{d2.dtype}\n')
print(d2)

(2, 3)
2
int64

[[1 5 4]
 [4 3 7]]


In [31]:
# Array 3D
d3 = np.array([[1,5,4],[4,3,7],[6,2,8]])
print(f'{d3.shape}\n{d3.ndim}\n{d3.dtype}\n')
print(d3)



(3, 3)
2
int64

[[1 5 4]
 [4 3 7]
 [6 2 8]]
