In [1]:
import numpy as np

In [12]:
a = np.array([[1,2,3,4],[5,6,8,9]])
print(a)

[[1 2 3 4]
 [5 6 8 9]]


In [ ]:
a[0,2] # <- Array [row, column] 

np.int64(3)

In [26]:
a [0, :] # ':' -> Vai até o último item

array([1, 2, 3, 4])

In [27]:
a[:, 1] # ':' -> mostra tudo que tem na coluna 1

array([2, 6])